name: takvim
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cross_connectivity: ^1.1.0
  cupertino_icons: ^1.0.1
  firebase_core: 0.5.3
  firebase_database: ^4.4.0
  flag: ^3.2.0
  flutter_riverpod: ^0.12.1
  google_fonts: ^1.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  intl: ^0.16.1
  modal_progress_hud: ^0.1.3
  hooks_riverpod: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  hive_generator: ^0.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/data/languages/
