name: takvim
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.2+16


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  cloud_firestore: ^0.14.4
  firebase_core: ^0.5.3
  firebase_messaging: 6.0.16
  cross_connectivity: ^1.1.0
  cupertino_icons: 1.0.0
  firebase_database: ^4.4.0
  flag: 2.0.4
  flutter_riverpod: ^0.12.1
  font_awesome_flutter: ^8.11.0
  google_fonts: ^1.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  intl: ^0.16.1
  responsive_framework: ^0.0.14
  url_launcher: ^5.7.10
  collection: ^1.14.13
  strings: ^0.1.4
  equatable: ^1.2.6
  webview_flutter: ^1.0.7
  flutter_compass: ^0.5.1
  permission_handler: ^5.1.0+2
  flutter_qiblah: ^1.0.3+2
  compasstools: ^0.1.0

dependency_overrides:
  flutter_svg: 0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  flutter_launcher_icons: "^0.8.0"
  hive_generator: ^0.8.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon_adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/data/languages/
  fonts:
    - family: Courier-Prime
      fonts:
        - asset: fonts/courier-prime-sans.regular.ttf
    - family: Noto-Mono
      fonts:
        - asset: fonts/noto-mono.regular.ttf
