name: MyMosq
description: Follow your Mosque!

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.0+39


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  cross_connectivity: ^1.1.0
  cupertino_icons: 1.0.0
  flag: ^3.2.2
  flutter_riverpod: ^0.12.1
  font_awesome_flutter: ^8.11.0
  google_fonts: ^1.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  intl: ^0.16.1
  responsive_framework: ^0.0.14
  url_launcher: ^5.7.10
  collection: ^1.14.13
  strings: ^0.1.4
  equatable: ^1.2.6
  webview_flutter: ^1.0.7
  flutter_compass: ^0.5.1
  permission_handler: ^5.1.0+2
  compasstools: ^0.1.0
  geolocator: ^6.2.1
  flutter_qiblah: ^1.0.3+2
  linkwell: ^0.1.9
  flutter_svg: ^0.19.0
  numberpicker: ^2.1.0
  flutter_local_notifications: ^4.0.1+2
  mailer: ^3.3.0
  firebase_crashlytics: 0.2.4
  cloud_firestore: ^0.14.4
  firebase_core: ^0.5.3
  firebase_messaging: 6.0.16
  firebase_database: ^4.4.0
  share: 0.6.5
  cloud_functions: 0.7.0
  store_redirect: ^2.0.0
  device_info: ^2.0.1
  geocoder: ^0.2.1
# dependency_overrides:
#   flutter_svg: 0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  flutter_launcher_icons: "^0.8.0"
  hive_generator: ^0.8.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon_adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/data/languages/
    - assets/images/
  fonts:
    - family: Courier-Prime
      fonts:
        - asset: fonts/courier-prime-sans.regular.ttf
    - family: Noto-Mono
      fonts:
        - asset: fonts/noto-mono.regular.ttf
